### ISSUE TITLE
在新的vuepress2中好像无法使用

### ISSUE THREAD

**Issue by dalaoshi777** [monsat/vuepress-plugin-use-pages#1]
![image](https://user-images.githubusercontent.com/47414347/173352851-7c99340b-fd33-4a30-9a09-1a608afac40f.png)
![image](https://user-images.githubusercontent.com/47414347/173353062-881ada43-1a7b-45c9-ba09-553778ac2b30.png)
![image](https://user-images.githubusercontent.com/47414347/173354560-f779b379-98be-40f3-a685-495876e36620.png)

**Comment by monsat** [comment]
@dalaoshi777 Thank you for raising.
I didn't know the breaking changes for plugins.

The latest version (1.0.5) is supported them.
Probably fixed. Please try 😄

**Comment by dalaoshi777** [comment]
can be used normally👍👍

**Comment by monsat** [comment]
Thank you for your feedback 🎉
